apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  000-default.conf: |
    <VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        ProxyPreserveHost On
        ProxyPass / http://app-service:8080/
        ProxyPassReverse / http://app-service:8080/

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>
