apiVersion: v1
kind: Secret
metadata:
  name: secret
  labels:
    app: app
type: Opaque
stringData:
  db-url: pnp-rds.ckvfjfutrkfo.ap-northeast-2.rds.amazonaws.com
  db-username: pnp
  db-password: pnp12345
