name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::560971842042:role/GitHubActionsRole
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-northeast-2 | \
        docker login --username AWS --password-stdin 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com
    - name: Build Web image
      run: |
        docker build -t pnp-ecr docker/web/
        docker tag pnp-ecr 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/pnp-ecr:web-final

    - name: Push Web image
      run: |
        docker push 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/pnp-ecr:web-final

    - name: Build App image
      run: |
        docker build -t pnp-ecr docker/app/
        docker tag pnp-ecr 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/pnp-ecr:app-final

    - name: Push App image
      run: |
        docker push 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/pnp-ecr:app-final

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \ 
          --region ap-northeast-2 \
          --name pnp-cluster \
          --role-arn arn:aws:iam::560971842042:role/GitHubActionsRole 
        
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/web/
        kubectl apply -f k8s/app/
        kubectl apply -f k8s/hpa/

